name: InAccel
on:
  workflow_dispatch:
    inputs:
      cname:
        required: true
        default: dashboard.rancher.inaccel.com
      version:
        required: true
        default: 2.6.8
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Build
      run: scripts/build-hosted
      env:
        BASE: https://${{ github.event.inputs.cname }}
        DRONE_TAG: v${{ github.event.inputs.version }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        cname: ${{ github.event.inputs.cname }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/v${{ github.event.inputs.version }}
        force_orphan: true
        full_commit_message: ${{ github.event.head_commit.id }}
